Lots of improvements

diff --git a/scripts/dot b/scripts/dot
--- a/scripts/dot
+++ b/scripts/dot
@@ -15,6 +15,8 @@ godlygeek=godlygeek
 spiiph=spiiph
 tpope=tpope
 
+red=$(tput setaf 1)
+green=$(tput setaf 2)
 blue=$(tput setaf 4)
 bold=$(tput bold)
 reset=$(tput sgr0)
@@ -35,7 +37,7 @@ helpfiles=help
 vimfiles=vimfiles
 
 github='github.com'
-arg_plugins=(ln -sv)
+arg_plugins=(ln -svf)
 
 program="${0##*/}"
 
@@ -74,14 +76,14 @@ while [[ $1 == -* ]]; do
 
     case "$1" in
 
-                 --*=*) parse_option "$1";    shift;;
-               --links) arg_links="$1";       shift;;
-        --copy-plugins) arg_plugins=(cp -fv); shift;;
-        --move-plugins) arg_plugins=(mv -v);  shift;;
-        --omit-plugins) arg_omit=omit;        shift;;
-           # --verbose) arg_plugins=(  );     shift;;
-         -h|--help|-\?) show_help;            exit 0;;
-                    --) shift; break;;
+                 --*=*) parse_option "$1";                        shift;;
+               --links) arg_links="$1";                           shift;;
+        --copy-plugins) arg_plugins=(cp -v --remove-destination); shift;;
+        --move-plugins) arg_plugins=(mv -vf);                     shift;;
+        --omit-plugins) arg_omit=omit;                            shift;;
+           # --verbose) arg_plugins=(  );                         shift;;
+         -h|--help|-\?) show_help;                                exit 0;;
+                    --) shift;                                    break;;
                     -*) echo "invalid option: $1" 1>&2; show_help; exit 1;;
     esac
 done
@@ -91,31 +93,25 @@ command -v git >/dev/null 2>&1 && git=true
 copyRepo() { # {{{1
 
     local author="$1"
-    local destination="$2"
+    local repo_name="$2"
     local repo="$3"
+    local repo_parent="${repo%/*}"
 
-    [[ ! -d $destination ]] && mkdir -pv "$destination"
+    printf "\n%-50s" "${bold}Copying $repo_name repository$reset..."
 
-    printf "\n%-50s" "${bold}Copying $repo repository$reset..."
+    if wget -qP "$repo_parent" "http://github.com/$author/$repo_name/tarball/master"; then
 
-    if [[ -d $destination ]]; then
-
-        if wget -qP "$destination" "http://github.com/$author/$repo/tarball/master"; then
-
-            if
-                tar -zxf "$destination"/*"$author"*"$repo"*.tar.gz -C "$destination"
-                rm "$destination"/*"$author"*"$repo"*.tar.gz
-                mv "$destination"/{*"$author"*"$repo"*/,"$repo"}
-            then
-                printf "... [ ${bold}OK$reset ]\n"
-            else
-                printf "... [ ${bold}FAILED$reset ]: $? (tar, rm or mv)\n"
-            fi
+        if
+            tar -zxf "$repo_parent"/*"$author"*"$repo_name"*.tar.gz -C "$repo_parent"
+            rm "$repo_parent"/*"$author"*"$repo_name"*.tar.gz
+            mv "$repo_parent"/{*"$author"*"$repo_name"*/,"$repo_name"}
+        then
+            printf "... [ $bold${green}OK$reset ]\n"
         else
-            printf "... [ ${bold}FAILED$reset ]: network failure\n"
+            printf "... [ $bold${red}FAILED$reset ]: $? (tar, rm or mv)\n"
         fi
     else
-        printf "... [ ${bold}FAILED$reset ]: $destination folder couldn't be created\n"
+        printf "... [ $bold${red}FAILED$reset ]: network failure\n"
     fi
 }
 
@@ -150,8 +146,8 @@ choice() { # {{{1
 cloneRepo() { # {{{1
 
     local author="$1"
-    local repo="$2"
-    local destination="$3"
+    local repo_name="$2"
+    local repo="$3"
 
     if [[ $author == $me ]]; then
 
@@ -162,29 +158,29 @@ cloneRepo() { # {{{1
 
     if [[ $git ]]; then
 
-        printf "\n%-50s" "${bold}Cloning $repo repository$reset..."
+        printf "\n%-50s" "${bold}Cloning $repo_name repository$reset..."
 
-        if git clone -q "$remote_host$author/$repo.git" "$destination"; then
+        if git clone -q "$remote_host$author/$repo_name.git" "$repo"; then
 
-            printf "... [ ${bold}OK$reset ]\n"
+            printf "... [ $bold${green}OK$reset ]\n"
         else
-            printf "... [ ${bold}FAILED$reset: Git error ] - trying to copy instead\n"
-            copyRepo "$author" "${destination%/*}" "$repo"
+            printf "... [ $bold${red}FAILED$reset: Git error ] - trying to copy instead\n"
+            copyRepo "$author" "$repo_name" "$repo"
         fi
     else
         choice quit 'Git is not installed on this machine' \
         'I want to install git and retry later' \
         'I want to simply copy the repositories'
 
-        copyRepo "$author" "${destination%/*}" "$repo"
+        copyRepo "$author" "$repo_name" "$repo"
     fi
 }
 
 pullRepo() { # {{{1
 
     local author="$1"
-    local repo="$2"
-    local destination="$3"
+    local repo_name="$2"
+    local repo="$3"
 
     if [[ $author == $me ]]; then
 
@@ -193,37 +189,37 @@ pullRepo() { # {{{1
         local remote_host="git://$github/"
     fi
 
-    if [[ -d $destination/.git ]]; then
+    if [[ -d $repo/.git ]]; then
 
         if [[ $git ]]; then
 
-            printf "\n%-50s" "${bold}Updating $repo repository$reset..."
+            printf "\n%-50s" "${bold}Updating $repo_name repository$reset..."
 
-            if git pull -q "$remote_host$author/$repo.git" master >/dev/null 2>&1; then
+            if git pull -q "$remote_host$author/$repo_name.git" master >/dev/null 2>&1; then
 
-                printf "... [ ${bold}OK$reset ]\n"
+                printf "... [ $bold${green}OK$reset ]\n"
             else
-                choice go_on "... [ ${bold}FAILED$reset: Git error ]" \
+                choice go_on "... [ $bold${red}FAILED$reset: Git error ]" \
                 'Abort' \
                 'I want to copy over the existing repository'
 
-                rm -rfv "$destination"
-                copyRepo "$author" "${destination%/*}" "$repo"
+                rm -rfv "$repo"
+                copyRepo "$author" "$repo_name" "$repo"
             fi
         else
-            choice quit "Cannot update $repo: Git is not installed" \
+            choice quit "Cannot update $repo_name: Git is not installed" \
             'I want to install git and retry later' \
             'I want to copy over the existing repositories'
 
-            rm -rfv "$destination"
-            copyRepo "$author" "${destination%/*}" "$repo"
+            rm -rfv "$repo"
+            copyRepo "$author" "$repo_name" "$repo"
         fi
     else
-        warn "$repo is not a Git working copy"
-        warn "overwriting $repo..."
+        warn "$repo_name is not a Git working copy"
+        warn "overwriting $repo_name..."
 
-        rm -rfv "$destination"
-        copyRepo "$author" "${destination%/*}" "$repo"
+        rm -rfv "$repo"
+        copyRepo "$author" "$repo_name" "$repo"
     fi
 }
 
@@ -235,8 +231,7 @@ linkToRepo() { # {{{1
 
     if [[ ! -e $dotfiles/$dotfile ]]; then
 
-        printf "\n\t"
-        ln -sv "$repo_dotfile" "$dotfiles"
+        printf "\n\t"; ln -sv "$repo_dotfile" "$dotfiles"
     else
         [[ -f $repo_dotfile ]] && local file='File'
         [[ -L $repo_dotfile ]] && local file='Link'
@@ -283,30 +278,33 @@ bash_dotfiles+=(.{bashrc,bashrc_after,bash_logout,logout,inputrc})
 help_dotfiles=(.{gitignore,screenrc,curlrc})
 vim_dotfiles=(.{vimrc,gvimrc})
 
-bash_repos="$repos/$bashfiles"
-help_repos="$repos/$helpfiles"
-vim_repos="$repos/$vimfiles"
+bash_repo="$repos/$bashfiles"
+help_repo="$repos/$helpfiles"
+vim_repo="$repos/$vimfiles"
 
-updateRepo "$me" "$bashfiles" "$bash_repos" "${bash_dotfiles[@]}"
-updateRepo "$me" "$helpfiles" "$help_repos" "${help_dotfiles[@]}"
-updateRepo "$me" "$vimfiles"  "$vim_repos"  "${vim_dotfiles[@]}"
+updateRepo "$me" "$bashfiles" "$bash_repo" "${bash_dotfiles[@]}"
+#updateRepo "$me" "$helpfiles" "$help_repo" "${help_dotfiles[@]}"
+updateRepo "$me" "$vimfiles"  "$vim_repo"  "${vim_dotfiles[@]}"
 
 # .vim -> vimfiles, _vimrc, _gvimrc
-if [[ -d $vim_repos ]]; then
+if [[ -d $vim_repo ]]; then
 
-    ln -sv "$vim_repos" "$dotfiles/.vim"
+    if [[ ! -L $dotfiles/.vim ]]; then
+
+        printf "\n\t"; ln -sv "$vim_repo" "$dotfiles/.vim"
+    fi
 
     if [[ ${arg_plugins[0]} == @(cp|mv) ]]; then
 
-        cp -fv "$vim_repos/.vimrc" "$dotfiles/_vimrc"
-        cp -fv "$vim_repos/.gvimrc" "$dotfiles/_gvimrc"
+        printf "\n\t"; cp -fv "$vim_repo/.vimrc" "$dotfiles/_vimrc"
+        printf "\n\t"; cp -fv "$vim_repo/.gvimrc" "$dotfiles/_gvimrc"
     fi
 fi
 
 # Vim plugins
 if [[ ! $arg_omit ]]; then
 
-    vim_plugins="$vim_repos/plugins"
+    vim_plugins="$vim_repo/plugins"
 
     updateRepo "$godlygeek" csapprox      "$vim_plugins/csapprox"
     updateRepo "$godlygeek" tabular       "$vim_plugins/tabular"
@@ -320,9 +318,10 @@ if [[ ! $arg_omit ]]; then
 
             while read -r -d $'\0'; do
 
-                reply=${REPLY##*$plugin/}
-                reply=${reply%/*}
-                "${arg_plugins[@]}" -- "$REPLY" "$vim_repos/$reply"
+                printf "\n\t"
+                file="${REPLY#*$plugin/}"
+                folder="${file%/*}"
+                "${arg_plugins[@]}" -- "$REPLY" "$vim_repo/$folder"
 
             done < <(find "$plugin" \( -name '*.vim' -o -name '*.txt' \) -print0)
 
@@ -331,13 +330,13 @@ if [[ ! $arg_omit ]]; then
 fi
 
 # Create a symlink of this script in ~/bin
-if [[ -d $bash_repos/scripts && ! -L $HOME/bin/$program ]]; then
+if [[ -d $bash_repo/scripts && ! -L $HOME/bin/$program ]]; then
 
     if [[ ! -d $HOME/bin ]]; then
 
-        mkdir -v "$HOME/bin" && ln -s "$bash_repos/scripts/$program" "$HOME/bin"
+        mkdir -v "$HOME/bin" && ln -s "$bash_repo/scripts/$program" "$HOME/bin"
     else
-        ln -s "$bash_repos/scripts/$program" "$HOME/bin"
+        ln -s "$bash_repo/scripts/$program" "$HOME/bin"
     fi
 fi
 
