%y -> %Y, iurl: echo/warn...

diff --git a/scripts/iurl b/scripts/iurl
--- a/scripts/iurl
+++ b/scripts/iurl
@@ -10,39 +10,42 @@ shopt -s extglob
 # Print a message to stderr
 warn() { echo "$@" >&2; }
 
-if [[ $# < 3 || '--help' == $3 ]]; then
+if (($# < 3)); then
 
-    warn "Usage: ${0##*/} (-w|--web-script OR -s|--schema OR -l|--library) (int|test|stage|live) files"
-    warn "       ${0##*/} --help: this help text"
+   warn "Usage: ${0##*/} (-w|--web-script OR -s|--schema OR -l|--library) (int|test|stage|live) files"
+   warn "       ${0##*/} --help: this help text"
+   exit 1
 
+elif [[ $3 == '--help' ]]; then
+
+   echo "Usage: ${0##*/} (-w|--web-script OR -s|--schema OR -l|--library) (int|test|stage|live) files"
+   echo "       ${0##*/} --help: this help text"
+   exit
 else
 
-    platform="$2"
+    platform=$2
 
-    project=org
-    certificate="/etc/pki/$project.pem"
-    prefix="${project}_"
+        project=org
+    certificate=/etc/pki/$project.pem
+         prefix=${project}_
 
-    schemas="https://.../Web%20Forms"
-    libraries="https://.../Web%20Forms/$project"
-    scripts="https://.../Web%20Scripts/$project"
+      schemas=https://.../Web%20Forms
+    libraries=https://.../Web%20Forms/$project
+      scripts=https://.../Web%20Scripts/$project
 
-    local_schemas="/mnt/.../schemas"
-    local_scripts="/mnt/.../widgets"
+    local_schemas=/mnt/.../schemas
+    local_scripts=/mnt/.../widgets
 
     # Schemas
     if [[ $1 == @(-s|--schema) ]]; then
 
         for arg in "${@:3}"; do
 
-            if
-                curl --cert "$certificate" -k -X PUT -T\
-                "$local_schemas/$prefix$arg.xsd"\
-                "$schemas/$prefix$arg/$prefix$arg.xsd"
-            then
-                echo "Uploaded the $arg schema."
-            else
-                echo "Failed to upload the $arg schema."
+            if curl --cert "$certificate" -k -X PUT -T \
+                    "$local_schemas/$prefix$arg.xsd" \
+              "$schemas/$prefix$arg/$prefix$arg.xsd"
+            then echo         "Uploaded the $arg schema."
+            else echo "Failed to upload the $arg schema."
             fi
         done
     fi
@@ -52,14 +55,11 @@ else
 
         for arg in "${@:3}"; do
 
-            if
-                curl --cert "$certificate" -k -X PUT -T\
-                "$local_schemas/$prefix$arg.xsd"\
-                "$libraries/$prefix$arg.xsd"
-            then
-                echo "Uploaded the $arg library."
-            else
-                echo "Failed to upload the $arg library."
+            if curl --cert "$certificate" -k -X PUT -T \
+                    "$local_schemas/$prefix$arg.xsd" \
+                        "$libraries/$prefix$arg.xsd"
+            then echo         "Uploaded the $arg library."
+            else echo "Failed to upload the $arg library."
             fi
         done
     fi
@@ -69,14 +69,11 @@ else
 
         for arg in "${@:3}"; do
 
-            if
-                curl --cert "$certificate" -k -X PUT -T\
-                "$local_scripts/$arg"\
-                "$scripts/$arg"
-            then
-                echo "Uploaded the $arg script."
-            else
-                echo "Failed to upload the $arg script."
+            if curl --cert "$certificate" -k -X PUT -T \
+                    "$local_scripts/$arg" \
+                          "$scripts/$arg"
+            then echo         "Uploaded the $arg script."
+            else echo "Failed to upload the $arg script."
             fi
         done
     fi
